version: "3.8"

services:
  app:
    restart: unless-stopped
    env_file:
      - .env
      - .env.production.local
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  postgresdb:
    ports:
      - "5432:5432"
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=unistack123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
